### ISSUE TITLE
Allow setting `required="true"` for `android.software.leanback`

### ISSUE THREAD

**Issue by matallui** [react-native-tvos/config-tv#17]
I'm building an Expo app which only targets Android TVs.
However, this plugin always seems to set

```xml
  <uses-feature android:name="android.software.leanback" android:required="false"/>
```

and, according to the Android docs,

> Declare that your app is for built for Android TV by declaring the android.software.leanback feature.
> If your app runs on both mobile and TV, set the required attribute value to false. If you set the required attribute value to true, Google Play will only make your app available on Android TV OS.

Can we provide a config plugin param that would enable this? Maybe something like `isAndroidTvOnly`?

**Comment by douglowder** [comment]
@matallui please take a look at #18 and see if that will work for you, and if you are aware of any other metadata that needs to be set for Android TV only apps. This change appears to do the right thing in local testing.

**Comment by matallui** [comment]
Confirmed that the changes from https://github.com/react-native-tvos/config-tv/pull/18 fix this issue.

**Comment by dev-folks** [comment]
Hello!

I also encountered a similar problem.

An interesting point is that when releasing in Google Play, "activities" are mixed.
https://www.reddit.com/r/AndroidTV/comments/1c598wu/my_android_tv_app_is_not_shown_on_google_play/?rdt=59442

The application will work and can be installed on the TV via a browser on a device with the same Google account as on the TV. However, on the TV itself, the application will be hidden in Google Play.

This happens because there are two launchers specified in the `activity` section of `AndroidManifest.xml`.
`<intent-filter>
    <action android:name="android.intent.action.MAIN"/>
    <category android:name="android.intent.category.LAUNCHER"/>
    <category android:name="android.intent.category.LEANBACK_LAUNCHER"/>
</intent-filter>`

https://developer.android.com/training/tv/get-started/create#tv-activity
the documentation says that to support tv you should add a new activity `TvActivity` with `LEANBACK_LAUNCHER`  however this also entails creating a class `TvActivity` - which also requires some knowledge about it.
Perhaps this relates to the potential functionality of the `config-tv` package. 


In my case, before the build, I simply deleted the standard `LAUNCHER`, leaving only `LEANBACK_LAUNCHER`. This worked for Google Play on TV, but the standard `LAUNCHER` is necessary for working with ReactNative (as far as I understand).

Am I right in my conclusions?
